name: Build Linux

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    # Install all dependencies BEFORE firewall is enabled
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libx11-dev \
          libxrandr-dev \
          libxinerama-dev \
          libxcursor-dev \
          libfreetype-dev \
          libgl1-mesa-dev \
          libasound2-dev \
          libfontconfig1-dev \
          libxext-dev \
          libxrender-dev \
          libxcomposite-dev \
          libsqlite3-dev \
          pkg-config
    
    # Install optional dependencies
    - name: Install optional dependencies
      run: |
        sudo apt-get install -y libchromaprint-dev || echo "Chromaprint not available, continuing without it"
    
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
    
    - name: Build
      run: |
        cd build
        make -j$(nproc)
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-build
        path: build/bin/
